# Generated by Django 2.1.5 on 2019-01-27 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('finished', 'finished'), ('in progress', 'in progress')], max_length=15)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskmanagment.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='taskmanagment.Area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='taskmanagment.Project'),
        ),
    ]
