# Generated by Django 2.1.5 on 2019-01-28 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
