# Generated by Django 2.1.5 on 2019-02-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagment', '0004_auto_20190129_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
