# Generated by Django 2.1.5 on 2019-02-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagment', '0006_auto_20190207_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='project',
        ),
    ]
