# Generated by Django 2.1.5 on 2019-03-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagment', '0009_auto_20190303_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
