# Generated by Django 2.1.5 on 2019-01-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
